# ShardingProxy 进行分库分表
#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
##    url: jdbc:mysql://172.16.10.132:3316/sharding_db?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
#    url: jdbc:mysql://172.16.10.132:3316/sharding_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: root

spring:
  shardingsphere:
    datasource:
      names: m1  # 虚拟数据库名称
      m1: # 配置对应实际库的属性
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3316/sharding_db?useSSL=false&serverTimezone=UTC
        username: root
        password: root
    props:
      sql:
        show: true

