# ShardingSphere 配置绑定表 , 绑定的两表的分库分表策略须一致，
# 例子： 订单表，订单详情表，以orderId 作为关联键
spring:
  shardingsphere:
    datasource:
      names: m1,m2  # 虚拟数据库名称 m0,m1
      m1: # 配置 m0 对应实际库的属性
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/coursedb?useSSL=false&serverTimezone=UTC
        username: root
        password: root
      m2: # 配置 m1 对应实际库的属性
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/coursedb2?useSSL=false&serverTimezone=UTC
        username: root
        password: root
    sharding:
      tables:
        t_dict:
          actualDataNodes: m$->{1..2}.t_dict_$->{1..2}
          keyGenerator:
            column: id
            type: SNOWFLAKE
            props: # 可不配置此属性 worker.id
              worker:
                id: 1
          databaseStrategy:
            inline:
              shardingColumn: status
              algorithmExpression: m$->{status}
          tableStrategy:
            inline:
              shardingColumn: status
              algorithmExpression: t_dict_$->{status}
        t_user:
          actualDataNodes: m$->{1..2}.t_user_$->{1..2}
          keyGenerator:
            column: user_id
            type: SNOWFLAKE
            props:
              worker:
                id: 1
          databaseStrategy:
            inline:
              shardingColumn: ustatus
              algorithmExpression: m$->{ustatus} # 分库策略
          tableStrategy:
            inline:
              shardingColumn: ustatus
              algorithmExpression: t_user_$->{ustatus} # 分表策略
      binding-tables: # 绑定表，当两表出现关系时，比如 一对一关系，需配置此属性。不然会出现笛卡尔积现象，出错
        - t_dict,t_user
    props:
      sql:
        show: true # 打印实时日志


