# ShardingSphere 单库多表的配置文件，course_1，course_2 表需要手动创建
spring:
  shardingsphere:
    datasource:
      names: m1  # 虚拟数据库名称
      m1:  # 配置对应实际库的属性
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/coursedb?useSSL=false&serverTimezone=UTC
        username: root
        password: root
    sharding:
      tables:    # 真实表对应分布设置
        course:  # 逻辑表
          actualDataNodes: m1.course_$->{1..2}  # 真实表分布(Groovy表达式) , sharding中的虚拟表 course 对应的是 m1库中的 course_1 ,course_2
          keyGenerator:  # 主键生成策略
            column: cid
            type: UUID  # 雪花算法 SNOWFLAKE /也可以设置 UUID
            props:
              worker: # 雪花算法需要的配置，可选
                id: 1
          tableStrategy: # 表策略
            inline:
              shardingColumn: cid  # 分片键
              algorithmExpression: course_$->{cid%2+1}  # 分片策略
    props:
      sql:
        show: true # 打印实时日志


